"use client";
import { useMemo, useRef, useState } from "react";
import Link from "next/link";
import { AlertTriangle, ArrowRight, Bot, BriefcaseBusiness, Check, CircleStop, Clock3, FileText, History, Loader2, MessageSquareText, RefreshCw, Send, ShieldCheck, Sparkles, Target, UserRound, WandSparkles } from "lucide-react";
import { applications } from "@/lib/career-data";
import { track } from "@/lib/analytics";
import type { AgentKind, AgentRun } from "@/lib/sprint4-data";
import { useCareerStore } from "./use-career-store";
import { useSprint4Store } from "./use-sprint4-store";

const agents: { id: AgentKind; name: string; role: string; icon: typeof Bot; color: string; suggestions: string[] }[] = [
  { id: "job-advisor", name: "AI 岗位顾问", role: "分析岗位、匹配度和申请优先级", icon: Target, color: "violet", suggestions: ["分析我当前最值得申请的岗位", "比较 NVIDIA 和 Anthropic 的机会"] },
  { id: "application-assistant", name: "AI 申请助手", role: "准备简历、Cover Letter 和跟进材料", icon: FileText, color: "blue", suggestions: ["为 NVIDIA 申请生成下一步计划", "检查我的申请材料是否完整"] },
  { id: "interview-coach", name: "AI 面试教练", role: "模拟面试、STAR 训练和能力反馈", icon: MessageSquareText, color: "orange", suggestions: ["根据短板安排本周面试训练", "帮我准备 Anthropic 技术面试"] },
  { id: "career-planner", name: "AI 职业规划师", role: "结合画像和求职进度制定长期计划", icon: WandSparkles, color: "green", suggestions: ["总结我本周的求职进展", "制定未来 30 天求职计划"] },
];
export function AICareerHub() {
  const { store: careerStore, setStore: setCareerStore } = useCareerStore(); const { store, setStore } = useSprint4Store();
  const [agent, setAgent] = useState<AgentKind>("job-advisor"); const [prompt, setPrompt] = useState(""); const [selectedRun, setSelectedRun] = useState<AgentRun | null>(null); const controller = useRef<AbortController | null>(null);
  const currentAgent = agents.find((item) => item.id === agent)!; const history = useMemo(() => [...store.agentRuns].reverse(), [store.agentRuns]);
  async function run(input = prompt, retryOf?: AgentRun) { if (!input.trim()) return; const id = `agent-${Date.now()}`; const redacted = redact(input); const running: AgentRun = { id, agent, prompt: input, redactedPrompt: redacted, status: "running", createdAt: new Date().toISOString(), retryCount: retryOf ? retryOf.retryCount + 1 : 0 }; setStore((s) => ({ ...s, agentRuns: [...s.agentRuns, running], usage: { ...s.usage, aiCalls: s.usage.aiCalls + 1 } })); setSelectedRun(running); setPrompt(""); track("agent_run_start", { agent, redacted: redacted !== input, retry: running.retryCount }); controller.current = new AbortController(); const timer = setTimeout(() => controller.current?.abort(), 15000); try { const response = await fetch("/api/ai/agents", { method: "POST", signal: controller.current.signal, headers: { "content-type": "application/json" }, body: JSON.stringify({ agent, prompt: redacted, context: { profile: { completeness: careerStore.profileCompleteness, targetRoles: ["AI Engineer", "SDE"], visaStatus: "[REDACTED_UNCONFIRMED]" }, applications: applications.map(({ company, role, status }) => ({ company, role, status })), tasks: careerStore.tasks.filter((task) => task.status === "todo").slice(0, 5).map(({ title, priority }) => ({ title, priority })) } }) }); const result = await response.json(); const next: AgentRun = { ...running, status: result.pendingWrite ? "awaiting_confirmation" : "completed", result: result.result, pendingWrite: result.pendingWrite }; updateRun(next); setSelectedRun(next); track("agent_run_complete", { agent, status: next.status }); } catch (error) { const failed: AgentRun = { ...running, status: controller.current?.signal.aborted ? "cancelled" : "failed", result: controller.current?.signal.aborted ? "请求已取消或超过 15 秒。你可以安全重试。" : "Agent 暂时不可用，请重试。" }; updateRun(failed); setSelectedRun(failed); } finally { clearTimeout(timer); controller.current = null; } }
  function updateRun(run: AgentRun) { setStore((s) => ({ ...s, agentRuns: s.agentRuns.map((item) => item.id === run.id ? run : item) })); }
  function cancel() { controller.current?.abort(); }
  function confirmWrite(run: AgentRun) { if (!run.pendingWrite) return; if (run.pendingWrite.action === "create_today_task") { setCareerStore((s) => ({ ...s, tasks: [{ id: `agent-task-${Date.now()}`, title: run.pendingWrite!.label, description: "由 AI Career Agent 建议，经用户确认后创建。", status: "todo", priority: "medium", dueAt: new Date(Date.now() + 86400000).toISOString(), source: "automatic", actionType: "application", actionHref: "/applications", postponedCount: 0 }, ...s.tasks] })); } const completed = { ...run, status: "completed" as const, pendingWrite: undefined, result: `${run.result}\n\n✓ 已按你的确认执行写操作。` }; updateRun(completed); setSelectedRun(completed); track("agent_write_confirm", { agent: run.agent, action: run.pendingWrite.action }); }
  return <div className="ai-hub"><section className="ai-hub-hero"><div className="shell"><div><span className="section-label">AI CAREER OPERATING SYSTEM</span><h1>四位 AI Agent，一个连续的职业上下文</h1><p>自动读取你的职业画像与当前申请；任何写操作都需要你明确确认。</p></div><div className="context-status"><ShieldCheck size={19}/><span><b>Privacy Context Active</b><small>敏感信息自动脱敏 · 写操作需确认</small></span></div></div></section><div className="shell ai-hub-layout"><aside className="agent-picker"><span>CHOOSE AN AGENT</span>{agents.map(({ icon: Icon, ...item }) => <button className={agent === item.id ? `active ${item.color}` : ""} key={item.id} onClick={() => { setAgent(item.id); setSelectedRun(null); }}><div><Icon size={17}/></div><span><b>{item.name}</b><small>{item.role}</small></span><ArrowRight size={13}/></button>)}<div className="agent-context"><h3><Sparkles size={14}/>已读取上下文</h3><p><UserRound size={12}/>Career Profile · {careerStore.profileCompleteness}%</p><p><BriefcaseBusiness size={12}/>{applications.length} 条申请记录</p><p><Check size={12}/>{careerStore.tasks.filter((t) => t.status === "todo").length} 项待办任务</p></div></aside><main className="agent-chat"><div className="agent-chat-head"><div className={`agent-avatar ${currentAgent.color}`}><currentAgent.icon size={20}/></div><div><h2>{currentAgent.name}</h2><p>{currentAgent.role}</p></div><span><i/>READY</span></div><div className="chat-body">{selectedRun ? <RunResult run={selectedRun} retry={() => run(selectedRun.prompt, selectedRun)} confirm={() => confirmWrite(selectedRun)} cancel={cancel}/> : <div className="agent-welcome"><div className={`agent-large-icon ${currentAgent.color}`}><currentAgent.icon size={28}/></div><h2>你好，我是{currentAgent.name}</h2><p>我会基于你已经确认的画像、申请与任务提供建议。试试下面的问题：</p><div>{currentAgent.suggestions.map((item) => <button key={item} onClick={() => run(item)}>{item}<ArrowRight size={13}/></button>)}</div></div>}</div><div className="agent-input"><div className="redaction-note"><ShieldCheck size={12}/>邮箱、手机号、证件号将在发送前自动脱敏</div><div><textarea value={prompt} onChange={(e) => setPrompt(e.target.value)} placeholder={`向${currentAgent.name}提问…`} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); run(); } }}/><button onClick={() => run()}><Send size={16}/></button></div></div></main><aside className="agent-history"><h3><History size={15}/>AI 任务历史</h3>{history.length ? history.slice(0, 12).map((item) => <button key={item.id} onClick={() => { setAgent(item.agent); setSelectedRun(item); }}><span className={`run-status ${item.status}`}/><div><b>{agents.find((a) => a.id === item.agent)?.name}</b><p>{item.prompt}</p><small>{new Date(item.createdAt).toLocaleString("zh-CN")} · {statusLabel(item.status)}</small></div></button>) : <div className="history-empty"><Bot size={23}/><p>完成的 Agent 任务会显示在这里。</p></div>}</aside></div></div>;
}
function RunResult({ run, retry, confirm, cancel }: { run: AgentRun; retry: () => void; confirm: () => void; cancel: () => void }) { return <div className="run-result"><div className="user-prompt"><span>YOU</span><p>{run.prompt}</p>{run.prompt !== run.redactedPrompt && <small><ShieldCheck size={11}/>敏感信息已脱敏后发送</small>}</div>{run.status === "running" ? <div className="agent-thinking"><Loader2 className="spin" size={19}/><div><b>Agent 正在分析你的职业上下文</b><span>读取画像与申请 → 形成建议 → 安全检查</span></div><button onClick={cancel}><CircleStop size={13}/>取消</button></div> : <div className={`agent-response ${run.status}`}><header><Sparkles size={15}/><b>Agent Response</b><span>{statusLabel(run.status)}</span></header><p>{run.result}</p>{run.pendingWrite && <div className="write-confirm"><AlertTriangle size={16}/><div><b>需要你的确认</b><p>Agent 请求执行写操作：{run.pendingWrite.label}</p></div><button onClick={confirm}>确认执行</button></div>}{["failed", "cancelled"].includes(run.status) && <button className="retry-run" onClick={retry}><RefreshCw size={14}/>重试任务</button>}</div>}</div>; }
function redact(value: string) { return value.replace(/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/g, "[EMAIL_REDACTED]").replace(/(?:\+?\d[\s-]?){8,15}/g, "[PHONE_REDACTED]").replace(/\b\d{15,18}[\dXx]\b/g, "[ID_REDACTED]"); }
function statusLabel(status: AgentRun["status"]) { return ({ running: "运行中", awaiting_confirmation: "等待确认", completed: "已完成", failed: "失败", cancelled: "已取消" } as Record<string, string>)[status]; }
