"use client";

import { useSearchParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { Check, Copy, FileText, Loader2, Save, ShieldCheck, Sparkles } from "lucide-react";
import { apiRequest, jsonBody } from "@/lib/api-client";

type Application={id:number;company:string;jobTitle:string};type Board={groups:Record<string,Application[]>};type ResumeOption={resumeId:number;resumeName:string;versionId:number;versionNo:number};type Material={id:number;type:string;status:string;content:string;updatedAt?:string};type Workspace={application:Application;resumeOptions:ResumeOption[];materials:Material[]};type Draft={id:number;materialType:string;materialLabel:string;status:string;content:string;resumeId:number;resumeVersionId:number};
const types=[{value:"cover_letter",label:"Cover Letter",desc:"完整求职信草稿"},{value:"why_company",label:"Why Company",desc:"为什么选择这家公司"},{value:"why_role",label:"Why Role",desc:"为什么适合这个岗位"},{value:"recruiter_message",label:"Recruiter Message",desc:"简洁的招聘方沟通消息"},{value:"follow_up_email",label:"Follow-up Email",desc:"申请或面试后的跟进邮件"}];
export function ApplicationMaterialsLive(){const search=useSearchParams();const initial=Number(search.get("applicationId"))||0;const [apps,setApps]=useState<Application[]>([]);const [appId,setAppId]=useState(initial);const [workspace,setWorkspace]=useState<Workspace|null>(null);const [resumeVersionId,setResumeVersionId]=useState(0);const [type,setType]=useState("cover_letter");const [draft,setDraft]=useState<Draft|null>(null);const [content,setContent]=useState("");const [confirmed,setConfirmed]=useState(false);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 const open=useCallback(async(id:number)=>{if(!id){setWorkspace(null);setLoading(false);return;}setLoading(true);setMessage("");try{const data=await apiRequest<Workspace>(`/api/v4/applications/${id}/workspace`);setWorkspace(data);setResumeVersionId(data.application&&data.resumeOptions.find(r=>r.versionId)?.versionId||data.resumeOptions[0]?.versionId||0);}catch(err){setMessage(err instanceof Error?err.message:"申请包加载失败");}finally{setLoading(false);}},[]);
 useEffect(()=>{apiRequest<Board>("/api/v4/applications/board").then(board=>{const list=Object.values(board.groups||{}).flat();setApps(list);const selected=initial||list[0]?.id||0;setAppId(selected);open(selected);}).catch(err=>{setMessage(err instanceof Error?err.message:"申请列表加载失败");setLoading(false);});},[initial,open]);
 async function generate(){if(!appId||!resumeVersionId||busy)return;const option=workspace?.resumeOptions.find(r=>r.versionId===resumeVersionId);if(!option)return;setBusy(true);setMessage("");setConfirmed(false);try{const result=await apiRequest<Draft>("/api/v4/materials/drafts",{method:"POST",body:jsonBody({applicationId:appId,resumeId:option.resumeId,resumeVersionId,materialType:type})});setDraft(result);setContent(String(result.content||""));}catch(err){setMessage(err instanceof Error?err.message:"草稿生成失败");}finally{setBusy(false);}}
 async function save(){if(!draft||!confirmed||busy)return;setBusy(true);setMessage("");try{await apiRequest(`/api/v4/materials/drafts/${draft.id}/confirm`,{method:"POST",body:jsonBody({content})});setMessage("已确认并保存到申请材料。");setDraft(null);setContent("");setConfirmed(false);await open(appId);}catch(err){setMessage(err instanceof Error?err.message:"保存失败");}finally{setBusy(false);}}
 async function reject(){if(!draft||busy)return;setBusy(true);try{await apiRequest(`/api/v4/materials/drafts/${draft.id}/reject`,{method:"POST",body:"{}"});setDraft(null);setContent("");setMessage("草稿已拒绝，未写入正式材料。");}catch(err){setMessage(err instanceof Error?err.message:"操作失败");}finally{setBusy(false);}}
 return <div className="zy-materials"><div className="zy-page-head"><div><h1>从真实经历出发，准备每一份申请材料。</h1><p>生成结果先作为草稿；只有在你核对、编辑并确认后，才会写入对应申请。</p></div><span className="zy-ai-safety"><ShieldCheck size={16}/>未经确认不写入</span></div>{message&&<p className={message.includes("已确认")||message.includes("已拒绝")?"zy-alert zy-success":"zy-alert"}>{message}</p>}{loading?<div className="zy-state-card"><Loader2 className="spin"/>正在读取申请包…</div>:<div className="zy-material-layout"><aside className="zy-material-setup"><label>选择申请<select value={appId} onChange={e=>{const id=Number(e.target.value);setAppId(id);setDraft(null);open(id);}}>{apps.map(app=><option value={app.id} key={app.id}>{app.company} · {app.jobTitle}</option>)}</select></label><label>简历版本<select value={resumeVersionId} onChange={e=>setResumeVersionId(Number(e.target.value))}>{workspace?.resumeOptions.map(option=><option value={option.versionId} key={option.versionId}>{option.resumeName} · V{option.versionNo}</option>)}</select></label><fieldset><legend>材料类型</legend>{types.map(item=><button type="button" className={type===item.value?"active":""} key={item.value} onClick={()=>{setType(item.value);setDraft(null);setContent("");}}><FileText size={16}/><span><b>{item.label}</b><small>{item.desc}</small></span>{type===item.value&&<Check size={14}/>}</button>)}</fieldset><button className="zy-button zy-button-primary" onClick={generate} disabled={busy||!resumeVersionId}>{busy?<Loader2 className="spin" size={15}/>:<Sparkles size={15}/>}生成可编辑草稿</button></aside><main className="zy-material-editor"><header><div><h2>{types.find(item=>item.value===type)?.label}</h2></div>{content&&<button onClick={()=>navigator.clipboard.writeText(content)}><Copy size={14}/>复制</button>}</header>{draft?<><textarea value={content} onChange={e=>{setContent(e.target.value);setConfirmed(false);}} aria-label="申请材料草稿"/><div className="zy-material-audit"><ShieldCheck size={16}/><p><b>请核对所有事实</b>AI 只应使用已确认简历内容。公司、岗位、经历、技能和任何数字都需要你再次确认。</p></div><label className="zy-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>我已阅读并确认内容真实准确</span></label><div className="zy-material-actions"><button className="zy-button zy-button-secondary" onClick={reject} disabled={busy}>拒绝草稿</button><button className="zy-button zy-button-primary" onClick={save} disabled={!confirmed||busy}><Save size={14}/>确认并保存</button></div></>:<div className="zy-material-empty"><Sparkles size={26}/><h2>申请材料将在这里生成</h2><p>选择申请、简历版本和材料类型。生成失败时不会创建空白成功记录。</p></div>}</main><aside className="zy-saved-materials"><h2>已保存材料 <span>{workspace?.materials?.length||0}</span></h2>{workspace?.materials?.length?workspace.materials.map(item=><article key={item.id}><b>{types.find(t=>t.value===item.type)?.label||item.type}</b><p>{String(item.content||"").slice(0,100)}{String(item.content||"").length>100?"…":""}</p><small>{item.updatedAt||item.status}</small></article>):<p>这条申请还没有已保存材料。</p>}</aside></div>}</div>}
