"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, BarChart3, BookOpenCheck, BrainCircuit, CalendarClock, Check, CheckCircle2, ChevronRight, CircleStop, Clock3, Code2, History, Loader2, MessageSquareText, Play, RotateCcw, Sparkles, Star, Target, Trophy, X } from "lucide-react";
import { track } from "@/lib/analytics";
import type { InterviewQuestionType, InterviewSession } from "@/lib/sprint4-data";
import { useCareerStore } from "./use-career-store";
import { useSprint4Store } from "./use-sprint4-store";

const tabs: { id: InterviewQuestionType | "Overview" | "History"; label: string; icon: typeof Target }[] = [{ id: "Overview", label: "准备总览", icon: Target }, { id: "Company history", label: "历史面经", icon: BookOpenCheck }, { id: "Behavioral", label: "行为题", icon: MessageSquareText }, { id: "Algorithm", label: "算法题", icon: Code2 }, { id: "Role-specific", label: "岗位专项题", icon: BrainCircuit }, { id: "History", label: "训练与报告", icon: History }];
const preparationProgress: [string, number][] = [["历史面经", 80], ["高频问题", 66], ["算法题", 50], ["行为题", 75], ["岗位专项题", 60]];
export function InterviewWorkspaceView({ workspaceId }: { workspaceId: string }) {
  const { store, setStore } = useSprint4Store(); const { setStore: setCareerStore } = useCareerStore();
  const workspace = store.interviews.find((item) => item.id === workspaceId)!;
  const [tab, setTab] = useState<(typeof tabs)[number]["id"]>("Overview"); const [training, setTraining] = useState(false); const [mode, setMode] = useState<InterviewSession["mode"]>("Mock Interview"); const [questionIndex, setQuestionIndex] = useState(0); const [answer, setAnswer] = useState(""); const [feedback, setFeedback] = useState(""); const [finishedSession, setFinishedSession] = useState<InterviewSession | null>(null);
  const trainingQuestions = useMemo(() => workspace?.questions.filter((q) => mode === "STAR Practice" ? q.type === "Behavioral" : q.type !== "Company history").slice(0, 3) || [], [workspace, mode]);
  if (!workspace) return <div className="not-found"><span>404</span><h1>面试空间不存在</h1><Link href="/interviews" className="button button-primary">返回面试中心</Link></div>;
  function toggleQuestion(id: string) { setStore((s) => ({ ...s, interviews: s.interviews.map((space) => space.id === workspace.id ? { ...space, questions: space.questions.map((q) => q.id === id ? { ...q, completed: !q.completed } : q) } : space) })); }
  function startTraining(selectedMode: InterviewSession["mode"]) { setMode(selectedMode); setTraining(true); setQuestionIndex(0); setAnswer(""); setFeedback(""); track("interview_training_start", { workspace_id: workspace.id, mode: selectedMode }); }
  function submitAnswer() { if (answer.trim().length < 20) { setFeedback("回答还比较简短。补充具体背景、你的行动和最终结果后再继续。"); return; } setFeedback("单题反馈：内容与问题相关，建议先给出结论，再用 2–3 个关键行动支撑；减少背景铺垫。岗位关键词匹配良好。"); }
  function nextQuestion() { if (questionIndex < trainingQuestions.length - 1) { setQuestionIndex((i) => i + 1); setAnswer(""); setFeedback(""); } else finishTraining(); }
  function finishTraining() { const session: InterviewSession = { id: `session-${Date.now()}`, workspaceId: workspace.id, startedAt: new Date(Date.now() - 18 * 60000).toISOString(), completedAt: new Date().toISOString(), mode, status: "completed", scores: mode === "STAR Practice" ? { content: 76, structure: 68, delivery: 72, roleMatch: 81 } : { content: 82, structure: 74, delivery: 69, roleMatch: 86 }, feedback: ["内容证据充分，继续强化量化结果", "结构是当前短板，建议采用结论先行", "控制语速并减少填充词", "与岗位所需能力关联明确"] }; setStore((s) => ({ ...s, usage: { ...s.usage, interviewSessions: s.usage.interviewSessions + 1 }, interviews: s.interviews.map((space) => space.id === workspace.id ? { ...space, readiness: Math.min(100, space.readiness + 8), sessions: [...space.sessions, session] } : space) })); const weakest = Object.entries(session.scores!).sort((a, b) => a[1] - b[1])[0][0]; setCareerStore((s) => ({ ...s, tasks: s.tasks.some((t) => t.id === `weakness-${workspace.id}-${weakest}`) ? s.tasks : [{ id: `weakness-${workspace.id}-${weakest}`, title: `提升面试${scoreLabel(weakest)}能力`, description: `最新模拟面试中${scoreLabel(weakest)}得分最低，完成一次专项训练。`, status: "todo", priority: "high", dueAt: new Date(Date.now() + 86400000).toISOString(), source: "automatic", applicationId: workspace.applicationId, actionType: "interview", actionHref: `/interviews/${workspace.id}`, postponedCount: 0 }, ...s.tasks] })); setFinishedSession(session); setTraining(false); track("interview_training_complete", { workspace_id: workspace.id, mode, scores: session.scores }); }
  const completed = workspace.questions.filter((q) => q.completed).length; const filteredQuestions = workspace.questions.filter((q) => tab === "Overview" || tab === "History" ? true : q.type === tab);
  return <div className="interview-workspace"><div className="workspace-banner"><div className="shell"><Link href="/interviews"><ArrowLeft size={14}/>面试中心</Link><div><span className="interview-company">AN</span><div><small>{workspace.company} · {workspace.round}</small><h1>{workspace.role}</h1><p><CalendarClock size={13}/>{new Date(workspace.interviewAt).toLocaleString("zh-CN")}</p></div></div><button onClick={() => startTraining("Mock Interview")}><Play size={15}/>开始模拟面试</button></div></div><div className="shell interview-layout"><aside className="interview-nav">{tabs.map(({ icon: Icon, ...item }) => <button className={tab === item.id ? "active" : ""} key={item.id} onClick={() => setTab(item.id)}><Icon size={15}/>{item.label}<ChevronRight size={13}/></button>)}<div className="interview-progress"><span>准备完成度 <b>{workspace.readiness}%</b></span><i><em style={{ width: `${workspace.readiness}%` }}/></i><small>{completed}/{workspace.questions.length} 道题已完成</small></div></aside><main className="interview-main">{tab === "Overview" ? <Overview workspace={workspace} startTraining={startTraining}/> : tab === "History" ? <TrainingHistory sessions={workspace.sessions}/> : <><div className="interview-main-head"><div><span className="section-label">QUESTION BANK</span><h2>{tabs.find((item) => item.id === tab)?.label}</h2></div><span>{filteredQuestions.length} 道题</span></div><div className="question-list">{filteredQuestions.map((question) => <article key={question.id}><button className={question.completed ? "done" : ""} onClick={() => toggleQuestion(question.id)}>{question.completed && <Check size={12}/>}</button><div><span>{question.frequency} Frequency · {question.type}</span><h3>{question.question}</h3><footer><button onClick={() => startTraining(question.type === "Behavioral" ? "STAR Practice" : "Mock Interview")}><Play size={12}/>练习这道题</button><button>查看思路</button></footer></div></article>)}</div></>}</main><aside className="interview-aside"><div className="countdown"><Clock3 size={17}/><span><b>距离面试还有 3 天</b><small>建议每天完成 2–3 道专项题</small></span></div><div className="rounds"><h3>面试轮次</h3>{["Recruiter Screen", "Technical", "Hiring Manager", "Final"].map((round, i) => <div className={round === workspace.round ? "current" : i === 0 ? "passed" : ""} key={round}><span>{i === 0 ? <Check size={11}/> : i + 1}</span><b>{round}</b></div>)}</div><div className="company-insight"><Sparkles size={15}/><h3>历史面经洞察</h3><p>候选人反馈研究深度和开放问题占比较高，算法题更重视沟通过程。</p></div></aside></div>{training && <TrainingModal mode={mode} question={trainingQuestions[questionIndex]?.question} index={questionIndex} total={trainingQuestions.length} answer={answer} setAnswer={setAnswer} feedback={feedback} submit={submitAnswer} next={nextQuestion} cancel={() => setTraining(false)}/>} {finishedSession && <ReportModal session={finishedSession} close={() => setFinishedSession(null)}/>}</div>;
}
function Overview({ workspace, startTraining }: { workspace: NonNullable<ReturnType<typeof useSprint4Store>["store"]["interviews"][number]>; startTraining: (mode: InterviewSession["mode"]) => void }) { const latest = workspace.sessions.filter((s) => s.status === "completed").at(-1); return <><div className="interview-main-head"><div><span className="section-label">PREPARATION OVERVIEW</span><h2>本轮准备重点</h2></div></div><div className="prep-actions"><button onClick={() => startTraining("Mock Interview")}><BrainCircuit size={20}/><span><b>岗位模拟面试</b><small>3 道题 · 约 20 分钟</small></span><ArrowRight size={15}/></button><button onClick={() => startTraining("STAR Practice")}><Star size={20}/><span><b>STAR 案例训练</b><small>行为题结构专项</small></span><ArrowRight size={15}/></button></div><div className="readiness-breakdown"><h3>准备进度</h3>{preparationProgress.map((item) => <div key={String(item[0])}><span>{item[0]}</span><i><em style={{ width: `${item[1]}%` }}/></i><b>{item[1]}%</b></div>)}</div>{latest?.scores && <div className="latest-report"><div><BarChart3 size={17}/><span><b>最近一次能力报告</b><small>{new Date(latest.completedAt!).toLocaleDateString("zh-CN")}</small></span></div><div>{Object.entries(latest.scores).map(([key, score]) => <span key={key}><b>{score}</b><small>{scoreLabel(key)}</small></span>)}</div></div>}</>; }
function TrainingHistory({ sessions }: { sessions: InterviewSession[] }) { return <><div className="interview-main-head"><div><span className="section-label">TRAINING HISTORY</span><h2>训练记录与能力趋势</h2></div></div><div className="trend-chart"><h3>横向能力趋势</h3><div className="trend-bars">{["内容", "结构", "表达", "岗位匹配"].map((label, index) => <div key={label}><span>{label}</span>{sessions.filter((s) => s.scores).map((session) => <i key={session.id} style={{ height: `${Object.values(session.scores!)[index]}%` }} title={`${Object.values(session.scores!)[index]} 分`}/>)}</div>)}</div><footer><span/><small>历史训练</small><span/><small>最近训练</small></footer></div><div className="history-list">{[...sessions].reverse().map((session) => <article key={session.id}><span><Trophy size={16}/></span><div><h3>{session.mode}</h3><p>{new Date(session.startedAt).toLocaleString("zh-CN")} · {session.status}</p></div>{session.scores && <b>{Math.round(Object.values(session.scores).reduce((a, b) => a + b, 0) / 4)}<small>总分</small></b>}</article>)}</div></>; }
function TrainingModal({ mode, question, index, total, answer, setAnswer, feedback, submit, next, cancel }: { mode: string; question?: string; index: number; total: number; answer: string; setAnswer: (v: string) => void; feedback: string; submit: () => void; next: () => void; cancel: () => void }) { return <div className="training-overlay"><div className="training-shell"><header><div><Sparkles size={17}/><span><b>AI Interview Coach</b><small>{mode} · Question {index + 1}/{total}</small></span></div><button onClick={cancel}><CircleStop size={16}/>结束训练</button></header><main><div className="ai-interviewer"><span>AI</span><p>{question}</p></div><textarea value={answer} onChange={(e) => setAnswer(e.target.value)} placeholder="输入你的回答。建议使用语音转文字，或按 STAR 结构组织内容……" autoFocus/>{feedback && <div className="single-feedback"><Sparkles size={15}/>{feedback}</div>}<div className="training-actions"><span><Clock3 size={13}/>建议回答 2–3 分钟</span>{feedback ? <button onClick={next}>{index === total - 1 ? "完成并生成报告" : "下一题"}<ArrowRight size={14}/></button> : <button onClick={submit}>提交回答并获取反馈 <ArrowRight size={14}/></button>}</div></main></div></div>; }
function ReportModal({ session, close }: { session: InterviewSession; close: () => void }) { return <div className="modal-backdrop"><div className="report-modal"><button className="report-close" onClick={close}><X size={17}/></button><div className="report-hero"><Trophy size={28}/><span>INTERVIEW REPORT</span><h2>本次训练总体得分</h2><strong>{Math.round(Object.values(session.scores!).reduce((a, b) => a + b, 0) / 4)}</strong><p>报告已保存，最低能力项已自动加入 Today 任务。</p></div><div className="score-quadrants">{Object.entries(session.scores!).map(([key, score]) => <div key={key}><b>{score}</b><span>{scoreLabel(key)}</span><i><em style={{ width: `${score}%` }}/></i></div>)}</div><div className="report-feedback"><h3>总体反馈</h3>{session.feedback?.map((item) => <p key={item}><CheckCircle2 size={13}/>{item}</p>)}</div><button className="button button-primary" onClick={close}>查看完整训练记录</button></div></div>; }
function scoreLabel(key: string) { return ({ content: "内容", structure: "结构", delivery: "表达", roleMatch: "岗位匹配" } as Record<string, string>)[key] || key; }
