"use client";

import { FormEvent, useEffect, useState } from "react";
import { CheckCircle2, Loader2, Save, ShieldCheck } from "lucide-react";
import { apiRequest, jsonBody } from "@/lib/api-client";

type Profile={school:string;major:string;degree:string;graduationYear:string;country:string;city:string;visaStatus:string;workAuthorization:string;sponsorNeeded:boolean;targetRoles:string[];targetIndustries:string[];targetCities:string[];employmentTypes:string[];skills:string[];completion:number;updatedAt?:string};
const join=(value?:string[])=>value?.join("、")||"";const split=(value:FormDataEntryValue|null)=>String(value||"").split(/[、,，;；\n]+/).map(v=>v.trim()).filter(Boolean);
export function ProfileLive(){const [profile,setProfile]=useState<Profile|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");useEffect(()=>{apiRequest<Profile>("/api/v4/profile").then(setProfile).catch(err=>setMessage(err instanceof Error?err.message:"画像加载失败")).finally(()=>setLoading(false));},[]);async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;setBusy(true);setMessage("");const f=new FormData(event.currentTarget);try{const next=await apiRequest<Profile>("/api/v4/profile",{method:"PUT",body:jsonBody({school:f.get("school"),major:f.get("major"),degree:f.get("degree"),graduationYear:f.get("graduationYear"),country:f.get("country"),city:f.get("city"),visaStatus:f.get("visaStatus"),workAuthorization:f.get("workAuthorization"),sponsorNeeded:f.get("sponsorNeeded")==="on",targetRoles:split(f.get("targetRoles")),targetIndustries:split(f.get("targetIndustries")),targetCities:split(f.get("targetCities")),employmentTypes:split(f.get("employmentTypes")),skills:split(f.get("skills"))})});setProfile(next);setMessage("职业画像已保存。");}catch(err){setMessage(err instanceof Error?err.message:"保存失败");}finally{setBusy(false);}}
 if(loading)return <div className="zy-state-card"><Loader2 className="spin"/>正在读取职业画像…</div>;if(!profile)return <div className="zy-alert">{message||"职业画像暂时无法读取。"}</div>;return <div className="zy-profile-live"><div className="zy-page-head"><div><h1>让岗位、简历和申请，围绕同一份真实背景工作。</h1><p>这里只保存你主动确认的信息。身份与签证字段用于海外求职筛选；国内求职可以留空。</p></div><div className="zy-profile-score"><b>{profile.completion}%</b><span>画像完整度</span></div></div>{message&&<p className={message.includes("已保存")?"zy-alert zy-success":"zy-alert"}>{message}</p>}<form className="zy-profile-form zy-form" onSubmit={save}><section><header><span className="zy-icon-box"><CheckCircle2 size={20}/></span><div><h2>教育信息</h2><p>用于判断校招资格与毕业时间。</p></div></header><div className="zy-form-row"><label>学校<input name="school" defaultValue={profile.school}/></label><label>专业<input name="major" defaultValue={profile.major}/></label></div><div className="zy-form-row"><label>学历<input name="degree" defaultValue={profile.degree}/></label><label>毕业年份<input name="graduationYear" defaultValue={profile.graduationYear}/></label></div></section><section><header><span className="zy-icon-box"><Save size={20}/></span><div><h2>求职目标</h2><p>使用顿号或逗号分隔多个选项。</p></div></header><label>目标岗位<input name="targetRoles" defaultValue={join(profile.targetRoles)} placeholder="产品经理、数据分析、软件工程"/></label><div className="zy-form-row"><label>目标城市<input name="targetCities" defaultValue={join(profile.targetCities)}/></label><label>工作类型<input name="employmentTypes" defaultValue={join(profile.employmentTypes)} placeholder="全职、实习"/></label></div><label>行业方向<input name="targetIndustries" defaultValue={join(profile.targetIndustries)}/></label><label>技能<input name="skills" defaultValue={join(profile.skills)}/></label></section><section><header><span className="zy-icon-box"><ShieldCheck size={20}/></span><div><h2>地区与身份信息</h2><p>只在你需要海外求职与 Sponsor 筛选时填写。</p></div></header><div className="zy-form-row"><label>国家 / 地区<input name="country" defaultValue={profile.country}/></label><label>城市<input name="city" defaultValue={profile.city}/></label></div><div className="zy-form-row"><label>签证状态<input name="visaStatus" defaultValue={profile.visaStatus}/></label><label>工作许可<input name="workAuthorization" defaultValue={profile.workAuthorization}/></label></div><label className="zy-inline-check"><input name="sponsorNeeded" type="checkbox" defaultChecked={profile.sponsorNeeded}/>需要雇主提供工作签证支持</label></section><button className="zy-button zy-button-primary" disabled={busy}>{busy?"正在保存…":<><Save size={15}/>保存职业画像</>}</button></form></div>}
