"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowRight, BookOpen, BriefcaseBusiness, ChevronRight, CircleAlert, ExternalLink, FileText, Headphones, HeartHandshake, Loader2, Mail, MapPin, MessageSquareText, Search, Send, ShieldCheck, Sparkles, Target, UsersRound } from "lucide-react";
import { apiRequest, jsonBody } from "@/lib/api-client";

function ResourceHero({ eyebrow, title, text, icon }: { eyebrow: string; title: React.ReactNode; text: string; icon: React.ReactNode }) {
  return <section className="zy-resource-hero"><div className="shell"><span>{icon}{eyebrow}</span><h1>{title}</h1><p>{text}</p></div></section>;
}
function LoadState({ loading, error, empty }: { loading: boolean; error: string; empty?: boolean }) {
  if (loading) return <div className="zy-resource-state"><Loader2 className="spin" size={22}/><b>正在读取内容…</b></div>;
  if (error) return <div className="zy-resource-state" role="alert"><CircleAlert size={22}/><b>{error}</b></div>;
  if (empty) return <div className="zy-resource-state"><Search size={22}/><b>没有找到匹配内容</b><span>尝试减少筛选条件或更换关键词。</span></div>;
  return null;
}
function formatDate(value?: string) { if (!value) return "近期"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("zh-CN", { year: "numeric", month: "short", day: "numeric" }).format(date); }

type Experience = { id:string|number; userName?:string; author?:string; company?:string; position?:string; role?:string; type?:string; round?:string; title?:string; content?:string; tags?:string[]; likesCount?:number; commentsCount?:number; createdAt?:string };
type ExperienceResult = { list:Experience[]; total:number; source?:string };

export function InterviewExperiencesHub() {
  const [data,setData]=useState<ExperienceResult|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [query,setQuery]=useState(""); const [company,setCompany]=useState("全部公司");
  function load(){setLoading(true);setError("");apiRequest<ExperienceResult>("/api/experiences?page=1&pageSize=40").then(setData).catch((err)=>setError(err instanceof Error?err.message:"面经数据加载失败")).finally(()=>setLoading(false));}
  useEffect(load,[]); const items=useMemo(()=>data?.list||[],[data]); const companies=useMemo(()=>Array.from(new Set(items.map((item)=>item.company).filter(Boolean))) as string[],[items]);
  const filtered=useMemo(()=>items.filter((item)=>(company==="全部公司"||item.company===company)&&`${item.title||""} ${item.company||""} ${item.position||item.role||""} ${item.content||""}`.toLowerCase().includes(query.toLowerCase())),[items,query,company]);
  return <div className="zy-resource-page"><ResourceHero eyebrow="笔经面经" icon={<MessageSquareText size={15}/>} title={<>把真实复盘整理成<br/>下一次面试的准备清单。</>} text="按公司、岗位与轮次查看当前面经库，保留经验来源、时间和备考重点，并可直接进入 AI 面试继续训练。"/><main className="shell zy-resource-main"><div className="zy-resource-toolbar"><label><Search size={17}/><span className="sr-only">搜索面经</span><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="搜索公司、岗位或关键词"/></label><select aria-label="筛选公司" value={company} onChange={(event)=>setCompany(event.target.value)}><option>全部公司</option>{companies.map((item)=><option key={item}>{item}</option>)}</select></div><p className="zy-resource-source"><ShieldCheck size={14}/>{data?.total??0} 条面经 · {data?.source==="database+curated"?"数据库与精选面经库":"当前面经库"}。个人经验仅供备考参考。</p><LoadState loading={loading} error={error}/>{!loading&&!error&&<div className="zy-experience-layout"><section className="zy-experience-list"><header><span>面试复盘</span><b>{filtered.length} 条结果</b></header>{filtered.map((item)=><article key={item.id}><div className="zy-experience-meta"><span>{item.company||"公司待补充"}</span><span>{item.round||item.type||"面试"}</span><time>{formatDate(item.createdAt)}</time></div><h2>{item.title||`${item.company||"公司"} ${item.position||"岗位"} 面经`}</h2><p>{item.content||"内容待补充。"}</p><div className="zy-experience-footer"><div>{item.tags?.slice(0,4).map((tag)=><span key={tag}>#{tag}</span>)}</div><small>{item.userName||item.author||"匿名用户"} · {item.likesCount||0} 赞 · {item.commentsCount||0} 评论</small></div></article>)}<LoadState loading={false} error="" empty={!filtered.length}/></section><aside className="zy-experience-aside"><Sparkles size={24}/><h2>把面经变成模拟题</h2><p>带着目标岗位进入 AI 面试，围绕技术题、行为题和项目复盘继续练习。</p><Link className="zy-button zy-button-primary" href="/interviews">进入 AI 面试 <ArrowRight size={14}/></Link></aside></div>}</main></div>;
}

type Article={id:string|number;title:string;desc?:string;content?:string;source?:string;pubDate?:string;time?:string;type?:string;tags?:string[];url?:string;sourceUrl?:string;isOfficial?:boolean}; type ArticleResult={articles:Article[];source?:string};
export function BlogHub(){
  const[data,setData]=useState<ArticleResult|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[query,setQuery]=useState("");
  useEffect(()=>{apiRequest<ArticleResult>("/api/news?tab=tip&limit=72").then(setData).catch((err)=>setError(err instanceof Error?err.message:"攻略内容加载失败")).finally(()=>setLoading(false));},[]);const items=useMemo(()=>(data?.articles||[]).filter((item)=>item.type==="tip"||item.tags?.includes("攻略")),[data]);const filtered=items.filter((item)=>`${item.title} ${item.desc||""} ${item.content||""}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="zy-resource-page"><ResourceHero eyebrow="求职攻略" icon={<BookOpen size={15}/>} title={<>从准备到复盘，<br/>每一步都有具体方法。</>} text="整理职引现有求职知识库中的实用内容，覆盖简历、JD 匹配、投递管理、面试和身份风险。"/><main className="shell zy-resource-main"><div className="zy-resource-toolbar"><label><Search size={17}/><span className="sr-only">搜索攻略</span><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="搜索攻略主题"/></label><Link href="/news">查看全部资讯 <ArrowRight size={14}/></Link></div><p className="zy-resource-source"><ShieldCheck size={14}/>内容来自当前职引知识库；涉及政策与招聘要求时，请以官方来源为准。</p><LoadState loading={loading} error={error}/>{!loading&&!error&&<section className="zy-guide-index"><header><span>实用指南</span><b>{filtered.length} 篇</b></header>{filtered.map((article,index)=><article key={article.id}><span>{String(index+1).padStart(2,"0")}</span><div><div className="zy-guide-tags">{article.isOfficial&&<i>职引内容</i>}{article.tags?.slice(0,3).map((tag)=><i key={tag}>{tag}</i>)}</div><h2>{article.title}</h2><p>{article.desc||article.content?.slice(0,150)||"查看内容详情。"}</p><details><summary>展开阅读 <ChevronRight size={15}/></summary><div>{article.content||article.desc}</div></details></div><aside><time>{formatDate(article.pubDate||article.time)}</time>{(article.url||article.sourceUrl)&&<a href={article.url||article.sourceUrl} target="_blank" rel="noreferrer">原始来源 <ExternalLink size={13}/></a>}</aside></article>)}<LoadState loading={false} error="" empty={!filtered.length}/></section>}</main></div>;
}

type HelpItem={id:string;category:string;title:string;summary:string;answer:string;links?:Array<{label:string;href:string}>};type HelpResult={items:HelpItem[];categories?:string[];source?:string};
export function HelpCenterHub(){
  const[data,setData]=useState<HelpResult|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[query,setQuery]=useState("");const[category,setCategory]=useState("全部");
  useEffect(()=>{apiRequest<HelpResult>("/api/content/help-center").then(setData).catch((err)=>setError(err instanceof Error?err.message:"帮助内容加载失败")).finally(()=>setLoading(false));},[]);const items=data?.items||[];const categories=data?.categories||Array.from(new Set(items.map((item)=>item.category)));const filtered=items.filter((item)=>(category==="全部"||item.category===category)&&`${item.title} ${item.summary} ${item.answer}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="zy-resource-page"><ResourceHero eyebrow="帮助中心" icon={<Headphones size={15}/>} title={<>先查使用说明，<br/>再解决具体问题。</>} text="查看职位、简历、AI 面试、账号与数据相关说明；仍无法解决时，可以联系职引支持团队。"/><main className="shell zy-resource-main"><div className="zy-resource-toolbar"><label><Search size={17}/><span className="sr-only">搜索帮助内容</span><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="搜索问题，例如：如何修改简历"/></label><Link href="/contact">联系团队 <ArrowRight size={14}/></Link></div><div className="zy-help-categories" role="group" aria-label="帮助分类"><button className={category==="全部"?"active":""} onClick={()=>setCategory("全部")}>全部</button>{categories.filter((item)=>item!=="全部").map((item)=><button className={category===item?"active":""} onClick={()=>setCategory(item)} key={item}>{item}</button>)}</div><LoadState loading={loading} error={error}/>{!loading&&!error&&<div className="zy-help-layout"><section className="zy-help-list">{filtered.map((item)=><details key={item.id}><summary><span><small>{item.category}</small><b>{item.title}</b><em>{item.summary}</em></span><ChevronRight size={18}/></summary><div><p>{item.answer}</p>{item.links?.map((link)=><Link key={link.href} href={link.href}>{link.label} <ArrowRight size={13}/></Link>)}</div></details>)}<LoadState loading={false} error="" empty={!filtered.length}/></section><aside><h2>常用入口</h2><Link href="/jobs"><BriefcaseBusiness size={18}/><span><b>职位中心</b><small>搜索并核对职位</small></span></Link><Link href="/resume"><FileText size={18}/><span><b>我的简历</b><small>管理简历版本</small></span></Link><Link href="/interviews"><MessageSquareText size={18}/><span><b>AI 面试</b><small>按岗位继续训练</small></span></Link></aside></div>}</main></div>;
}

export function ContactHub(){
  const[form,setForm]=useState({name:"",email:"",subject:"商务合作",message:""});const[status,setStatus]=useState("");const[sending,setSending]=useState(false);
  async function submit(event:FormEvent){event.preventDefault();setSending(true);setStatus("");try{await apiRequest("/api/feedback",{method:"POST",body:jsonBody({type:form.subject,contact:`${form.name.trim()} / ${form.email.trim()}`,content:form.message.trim()})});setStatus("留言已提交，我们会尽快处理。");setForm({name:"",email:"",subject:"商务合作",message:""});}catch(err){setStatus(err instanceof Error?err.message:"提交失败，请稍后重试");}finally{setSending(false);}}
  return <div className="zy-resource-page"><ResourceHero eyebrow="联系我们" icon={<Mail size={15}/>} title={<>关于合作、产品或服务，<br/>都可以从这里联系。</>} text="提交商务合作、媒体采访、产品建议或使用问题。紧急问题也可以通过页面右侧的微信咨询联系。"/><main className="shell zy-resource-main"><div className="zy-contact-layout"><aside><section><Mail size={20}/><h2>电子邮件</h2><p>商务合作：<a href="mailto:bd@zhiyincareer.com">bd@zhiyincareer.com</a></p><p>用户支持：<a href="mailto:support@zhiyincareer.com">support@zhiyincareer.com</a></p></section><section><MapPin size={20}/><h2>服务范围</h2><p>面向大学生与应届毕业生提供求职信息、申请管理和面试准备支持。</p></section></aside><form onSubmit={submit}><header><span>在线留言</span><h2>告诉我们你的需求</h2></header><div className="zy-contact-row"><label>姓名<input required value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})}/></label><label>联系邮箱<input required type="email" value={form.email} onChange={(e)=>setForm({...form,email:e.target.value})}/></label></div><label>咨询类型<select value={form.subject} onChange={(e)=>setForm({...form,subject:e.target.value})}><option>商务合作</option><option>用户支持</option><option>媒体采访</option><option>产品建议</option></select></label><label>内容描述<textarea required rows={7} value={form.message} onChange={(e)=>setForm({...form,message:e.target.value})}/></label>{status&&<p className="zy-contact-status" role="status">{status}</p>}<button className="zy-button zy-button-primary" disabled={sending}>{sending?"提交中…":"发送消息"}<Send size={14}/></button></form></div></main></div>;
}

export function TeamHub(){return <div className="zy-resource-page"><ResourceHero eyebrow="关于职引" icon={<UsersRound size={15}/>} title={<>围绕真实求职流程，<br/>持续打磨产品。</>} text="职引面向大学生与应届毕业生，将职位发现、简历准备、申请管理与面试训练连接成一条可执行的路径。"/><main className="shell zy-resource-main"><section className="zy-team-intro"><div><span>产品使命</span><h2>让复杂的求职过程变得清楚、可追踪。</h2><p>机会判断、材料版本、申请状态和面试反馈经常分散在不同工具里。职引希望让这些信息围绕同一份职业上下文工作，减少重复整理和遗漏。</p></div><aside><Target size={32}/><b>面向所有大学生</b><p>覆盖国内求职，也保留留学生需要的地区、身份与签证信息。</p></aside></section><section className="zy-team-values"><article><HeartHandshake size={22}/><h3>用户导向</h3><p>先解决真实求职流程中的具体问题。</p></article><article><ShieldCheck size={22}/><h3>信息可核验</h3><p>保留职位、政策与内容的来源入口。</p></article><article><Sparkles size={22}/><h3>AI 有边界</h3><p>AI 提供建议，关键决定由用户确认。</p></article></section></main></div>}

const privacySections=[
  ["1. 我们如何收集您的个人信息","注册登录可能使用手机号或邮箱；简历与求职功能可能包含教育背景、经历、项目、技能和联系方式；AI 面试只会在获得设备权限后处理语音、视频或文本作答。"],
  ["2. 我们如何使用信息","用于提供职位匹配、简历分析、面试反馈、申请管理、安全风控及产品服务。"],
  ["3. 第三方平台与数据共享","未经明确同意，我们不会出售或出租个人可识别信息。主动投递时，相关企业可能获得您选择提交的简历信息；法律法规另有要求的除外。"],
  ["4. 如何管理您的信息","您可以在账号与简历功能中访问和更新信息；如需删除数据或注销账号，可联系支持团队。"],
  ["5. 联系我们","隐私问题请发送邮件至 privacy@zhiyin.com。"],
];
const termSections=[
  ["一、账号注册与使用","注册资料应真实、准确、合法有效；请妥善保管账号与密码，发现未经授权使用时应及时联系平台。"],
  ["二、平台服务与 AI 功能","AI 简历优化、模拟面试与相关分析仅供参考，不代表求职结果保证。职位、薪资与政策信息应以企业和官方渠道为准。"],
  ["三、用户行为规范","不得发布违法、欺诈、侵权或垃圾信息，不得利用非法接口、爬虫或其他手段破坏平台与数据。"],
  ["四、知识产权","平台软件、文本、图像和其他内容的权利归平台或合法授权方所有，未经许可不得复制或商业使用。"],
  ["五、条款修改与终止","条款调整将通过页面公布。继续使用服务前，请关注更新内容并自行判断是否接受。"],
];
export function LegalHub({type}:{type:"privacy"|"terms"}){const privacy=type==="privacy";const sections=privacy?privacySections:termSections;return <div className="zy-resource-page"><ResourceHero eyebrow={privacy?"隐私政策":"服务条款"} icon={privacy?<ShieldCheck size={15}/>:<FileText size={15}/>} title={privacy?"隐私政策":"服务条款"} text={privacy?"了解职引对个人信息的收集、使用、保存和保护方式。":"了解账号使用、平台服务、AI 功能边界与用户行为规范。"}/><main className="shell zy-legal-main"><header><span>{privacy?"最后更新日期：2024 年 03 月 20 日":"生效日期：2024 年 01 月 01 日"}</span><p>{privacy?"欢迎使用职引。本政策说明我们如何处理您在使用服务时提供的信息。":"欢迎使用职引。使用平台服务前，请阅读并理解以下内容。"}</p></header>{sections.map(([title,text])=><section key={title}><h2>{title}</h2><p>{text}</p></section>)}</main></div>}
