"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AlertCircle, ArrowRight, Bell, BellRing, BriefcaseBusiness, CalendarClock, Check, CheckCircle2, ChevronDown, CircleDollarSign, Clock3, Flame, Gift, ListTodo, MapPin, MoreHorizontal, Plus, RotateCcw, Settings2, ShieldCheck, Sparkles, Star, Target, Trophy, UserRound, X } from "lucide-react";
import { applications, type TaskPriority, type TodayTask } from "@/lib/career-data";
import { jobs } from "@/lib/jobs";
import { track } from "@/lib/analytics";
import { useCareerStore } from "./use-career-store";

type TaskView = "today" | "upcoming" | "completed";
const priorityLabel = { high: "高优先级", medium: "中优先级", low: "低优先级" };

export function TodayDashboard() {
  const { store, setStore, ready } = useCareerStore();
  const [view, setView] = useState<TaskView>("today");
  const [createOpen, setCreateOpen] = useState(false);
  const [reminderOpen, setReminderOpen] = useState(false);
  const [title, setTitle] = useState("");
  const [priority, setPriority] = useState<TaskPriority>("medium");
  const [dueAt, setDueAt] = useState(toDateTimeInput(new Date(Date.now() + 3 * 3600000)));
  const [actionType, setActionType] = useState<TodayTask["actionType"]>("application");
  const [toast, setToast] = useState("");

  useEffect(() => { track("today_view"); }, []);
  useEffect(() => {
    if (!ready) return;
    setStore((current) => {
      const generated = generateStageTasks(current.tasks);
      return generated.length ? { ...current, tasks: [...current.tasks, ...generated] } : current;
    });
  }, [ready]); // one migration pass per session

  const applied = applications.filter((item) => !["Interested", "Preparing"].includes(item.status)).length;
  const interviewing = applications.filter((item) => item.status === "Interview").length;
  const offers = applications.filter((item) => item.status === "Offer").length;
  const goalProgress = Math.min(100, Math.round(applied / store.weeklyApplicationGoal * 100));
  const now = new Date(); const endToday = new Date(); endToday.setHours(23, 59, 59, 999);
  const visibleTasks = useMemo(() => store.tasks.filter((task) => view === "completed" ? task.status !== "todo" : task.status === "todo" && (view === "today" ? new Date(task.dueAt) <= endToday : new Date(task.dueAt) > endToday)).sort((a, b) => priorityRank(a.priority) - priorityRank(b.priority) || +new Date(a.dueAt) - +new Date(b.dueAt)), [store.tasks, view]);
  const completedToday = store.tasks.filter((task) => task.completedAt && new Date(task.completedAt).toDateString() === now.toDateString()).length;

  function updateTask(id: string, status: "completed" | "skipped") {
    setStore((current) => ({ ...current, tasks: current.tasks.map((task) => task.id === id ? { ...task, status, ...(status === "completed" ? { completedAt: new Date().toISOString() } : { skippedAt: new Date().toISOString() }) } : task) }));
    track(status === "completed" ? "task_complete" : "task_skip", { task_id: id }); setToast(status === "completed" ? "任务已完成，继续保持。" : "任务已跳过，可在已完成中查看。");
  }
  function postpone(id: string) { const next = new Date(); next.setDate(next.getDate() + 1); next.setHours(10, 0, 0, 0); setStore((current) => ({ ...current, tasks: current.tasks.map((task) => task.id === id ? { ...task, dueAt: next.toISOString(), postponedCount: task.postponedCount + 1 } : task) })); track("task_postpone", { task_id: id, days: 1 }); setToast("任务已延期至明天 10:00。"); }
  function createTask() { if (!title.trim()) return; const href = actionType === "resume" ? "/resume" : actionType === "job" ? "/jobs" : actionType === "profile" ? "/profile" : actionType === "interview" ? "/application-assistant" : "/applications"; const task: TodayTask = { id: `task-${Date.now()}`, title: title.trim(), description: "手动创建的求职任务", status: "todo", priority, dueAt: new Date(dueAt).toISOString(), source: "manual", actionType, actionHref: href, postponedCount: 0 }; setStore((current) => ({ ...current, tasks: [task, ...current.tasks] })); track("task_create", { priority, action_type: actionType }); setCreateOpen(false); setTitle(""); setToast("任务已加入今日计划。"); }

  return <div className="today-page"><section className="today-welcome"><div className="shell welcome-grid"><div><span className="date-label">TUESDAY · JULY 14</span><h1>早上好，Alex 👋</h1><p>今天有 <b>{store.tasks.filter((task) => task.status === "todo" && new Date(task.dueAt) <= endToday).length} 项任务</b>值得优先处理。保持节奏，你正在接近下一个 Offer。</p></div><div className="streak-card"><Flame size={21}/><span><b>7 DAY STREAK</b><small>连续行动第 7 天</small></span></div></div></section>
    <div className="shell today-content">{store.profileCompleteness < 100 && <div className="profile-alert"><div className="profile-alert-icon"><UserRound size={20}/></div><div><b>你的 Career Profile 已完成 {store.profileCompleteness}%</b><p>补充 Visa Status 和求职偏好，解锁更准确的 Sponsor 岗位推荐。</p><i><em style={{ width: `${store.profileCompleteness}%` }}/></i></div><Link href="/profile">继续完善 <ArrowRight size={14}/></Link></div>}
      <section className="weekly-overview"><div className="goal-card"><div className="goal-head"><span><Target size={18}/>本周投递目标</span><b>{applied}<small> / {store.weeklyApplicationGoal}</small></b></div><div className="goal-progress"><i><em style={{ width: `${goalProgress}%` }}/></i><span>{goalProgress}% 完成</span></div><p>{store.weeklyApplicationGoal - applied > 0 ? `再完成 ${store.weeklyApplicationGoal - applied} 份高质量申请，即可达成本周目标。` : "本周目标已完成！"}</p></div><MetricCard icon={BriefcaseBusiness} label="已投递" value={applied} change="本周 +2" color="violet"/><MetricCard icon={CalendarClock} label="面试中" value={interviewing} change="1 个待准备" color="orange"/><MetricCard icon={Trophy} label="Offer" value={offers} change="Keep going!" color="green"/></section>
      <div className="today-main-grid"><section className="today-tasks"><div className="today-section-head"><div><span className="section-label">ACTION CENTER</span><h2>今日任务</h2></div><div><button className="reminder-button" onClick={() => setReminderOpen(true)}>{store.reminderSettings.enabled ? <BellRing size={15}/> : <Bell size={15}/>}提醒设置</button><button className="button button-primary" onClick={() => setCreateOpen(true)}><Plus size={15}/>新建任务</button></div></div><div className="task-tabs"><button className={view === "today" ? "active" : ""} onClick={() => setView("today")}>今天</button><button className={view === "upcoming" ? "active" : ""} onClick={() => setView("upcoming")}>即将到来</button><button className={view === "completed" ? "active" : ""} onClick={() => setView("completed")}>已完成 <span>{completedToday}</span></button></div><div className="task-list">{visibleTasks.map((task) => <article className={`today-task priority-${task.priority}`} key={task.id}><button className="task-check" onClick={() => task.status === "todo" && updateTask(task.id, "completed")} aria-label="完成任务">{task.status === "completed" && <Check size={13}/>} {task.status === "skipped" && <X size={13}/>}</button><div className="task-copy"><div><span className={`priority-label ${task.priority}`}>{priorityLabel[task.priority]}</span>{task.source === "automatic" && <span className="auto-label"><Sparkles size={10}/>自动生成</span>}</div><h3>{task.title}</h3><p>{task.description}</p><footer><span><Clock3 size={12}/>{formatDue(task.dueAt)}</span>{task.applicationId && <span><BriefcaseBusiness size={12}/>{applications.find((app) => app.id === task.applicationId)?.company}</span>}<Link href={task.actionHref}>{task.actionType === "interview" ? "准备面试" : task.actionType === "resume" ? "打开简历" : "开始处理"}<ArrowRight size={12}/></Link></footer></div>{task.status === "todo" && <div className="task-menu"><button><MoreHorizontal size={16}/></button><div><button onClick={() => postpone(task.id)}><RotateCcw size={12}/>延期到明天</button><button onClick={() => updateTask(task.id, "skipped")}><X size={12}/>跳过任务</button></div></div>}</article>)}{visibleTasks.length === 0 && <div className="task-empty"><CheckCircle2 size={30}/><h3>{view === "today" ? "今天的任务已完成" : "这里暂时没有任务"}</h3><p>做得很好，去看看新的高匹配岗位吧。</p></div>}</div></section>
        <aside className="today-sidebar"><div className="focus-card"><div><Sparkles size={16}/><span>AI DAILY FOCUS</span></div><h3>先完成 NVIDIA 定制简历</h3><p>该岗位匹配度 92%，且申请正在准备中。预计需要 20 分钟。</p><Link href="/resume/resume-ai">开始处理 <ArrowRight size={13}/></Link></div><div className="activity-card"><h3>本周行动</h3><div><span>任务完成</span><b>{completedToday} / 5</b></div><div><span>简历优化</span><b>{store.resumes.reduce((n, r) => n + r.optimizationCount, 0)} 次</b></div><div><span>申请材料</span><b>{store.materials.length} 份</b></div></div></aside></div>
      <section className="job-intelligence"><div className="today-section-head"><div><span className="section-label">JOB INTELLIGENCE</span><h2>今天值得关注的机会</h2></div><Link href="/jobs">浏览全部岗位 <ArrowRight size={14}/></Link></div><div className="intel-columns"><JobIntel title="高匹配岗位" icon={Sparkles} jobs={jobs.filter((job) => job.match >= 84).slice(0, 3)} badge={(job) => `${job.match}% 匹配`}/><JobIntel title="即将截止" icon={Clock3} jobs={[jobs[3], jobs[5], jobs[1]]} badge={() => "3 天内截止"}/><JobIntel title="Sponsor 岗位" icon={ShieldCheck} jobs={jobs.filter((job) => job.visa.includes("H1B Sponsor") || job.sponsorLevel === "Strong").slice(0, 3)} badge={(job) => job.sponsorLevel}/></div></section>
      <section className="saved-updates"><div className="saved-title"><Star size={18}/><div><h2>收藏岗位更新</h2><p>你关注的岗位有 3 条新动态</p></div></div><div className="update-items"><div><span className="update-dot new"/><p><b>Stripe · Software Engineer Intern</b>申请截止时间提前至 8 月 8 日</p><small>2 小时前</small></div><div><span className="update-dot"/><p><b>NVIDIA · AI Engineer</b>新增 H1B Sponsor 标签</p><small>昨天</small></div><div><span className="update-dot"/><p><b>Shopify · Data Scientist</b>薪资范围已更新</p><small>昨天</small></div></div></section>
    </div>{toast && <button className="today-toast" onClick={() => setToast("")}><CheckCircle2 size={16}/>{toast}<X size={13}/></button>}{createOpen && <TaskModal title={title} setTitle={setTitle} priority={priority} setPriority={setPriority} dueAt={dueAt} setDueAt={setDueAt} actionType={actionType} setActionType={setActionType} onClose={() => setCreateOpen(false)} onSave={createTask}/>} {reminderOpen && <ReminderPanel store={store} setStore={setStore} onClose={() => setReminderOpen(false)} setToast={setToast}/>}</div>;
}

function MetricCard({ icon: Icon, label, value, change, color }: { icon: typeof Target; label: string; value: number; change: string; color: string }) { return <div className={`metric-card ${color}`}><div><Icon size={18}/></div><span>{label}</span><b>{value}</b><small>{change}</small></div>; }
function JobIntel({ title, icon: Icon, jobs: items, badge }: { title: string; icon: typeof Sparkles; jobs: typeof jobs; badge: (job: typeof jobs[number]) => string }) { return <div className="intel-card"><h3><Icon size={15}/>{title}</h3>{items.map((job) => <Link href={`/jobs/${job.id}`} key={job.id}><span className="company-logo" style={{ background: job.companyColor }}>{job.companyInitials}</span><div><b>{job.title}</b><small><MapPin size={10}/>{job.company} · {job.location}</small></div><em>{badge(job)}</em></Link>)}</div>; }
function TaskModal(props: { title: string; setTitle: (v: string) => void; priority: TaskPriority; setPriority: (v: TaskPriority) => void; dueAt: string; setDueAt: (v: string) => void; actionType: TodayTask["actionType"]; setActionType: (v: TodayTask["actionType"]) => void; onClose: () => void; onSave: () => void }) { return <div className="modal-backdrop"><div className="modal-card task-modal"><div className="modal-icon"><ListTodo size={21}/></div><h2>创建今日任务</h2><p>为任务设置优先级和截止时间，稍后可以延期或跳过。</p><label>任务名称<input autoFocus value={props.title} onChange={(e) => props.setTitle(e.target.value)} placeholder="例如：完成 NVIDIA Cover Letter"/></label><div className="two-fields"><label>优先级<select value={props.priority} onChange={(e) => props.setPriority(e.target.value as TaskPriority)}><option value="high">高优先级</option><option value="medium">中优先级</option><option value="low">低优先级</option></select></label><label>截止时间<input type="datetime-local" value={props.dueAt} onChange={(e) => props.setDueAt(e.target.value)}/></label></div><label>完成任务时跳转到<select value={props.actionType} onChange={(e) => props.setActionType(e.target.value as TodayTask["actionType"])}><option value="application">申请记录</option><option value="resume">简历中心</option><option value="job">职位中心</option><option value="interview">面试准备</option><option value="profile">职业画像</option></select></label><div><button className="button button-ghost" onClick={props.onClose}>取消</button><button className="button button-primary" onClick={props.onSave}>创建任务</button></div></div></div>; }
function ReminderPanel({ store, setStore, onClose, setToast }: { store: ReturnType<typeof useCareerStore>["store"]; setStore: ReturnType<typeof useCareerStore>["setStore"]; onClose: () => void; setToast: (v: string) => void }) { const settings = store.reminderSettings; function patch(value: Partial<typeof settings>) { setStore((s) => ({ ...s, reminderSettings: { ...s.reminderSettings, ...value } })); } async function save() { await fetch("/api/tasks/reminders", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ settings, tasks: store.tasks.filter((task) => task.status === "todo") }) }); track("reminder_settings_update", { enabled: settings.enabled, frequency: settings.frequency }); setToast("微信提醒偏好已保存，重复任务会自动去重。"); onClose(); } return <div className="modal-backdrop"><div className="modal-card reminder-modal"><div className="reminder-modal-head"><div className="modal-icon"><BellRing size={21}/></div><button onClick={onClose}><X size={17}/></button></div><h2>微信任务提醒</h2><p>通过微信订阅消息提醒重要任务。相同任务在同一提醒窗口只发送一次。</p><label className="reminder-toggle"><span><b>启用微信提醒</b><small>需要在微信内完成一次订阅授权</small></span><input type="checkbox" checked={settings.enabled} onChange={(e) => patch({ enabled: e.target.checked })}/><i/></label><label>提醒频率<select value={settings.frequency} onChange={(e) => patch({ frequency: e.target.value as typeof settings.frequency })}><option value="important">仅重要任务</option><option value="daily">每天一次</option><option value="twice_daily">每天两次</option></select></label><div className="two-fields"><label>早间提醒<input type="time" value={settings.morningTime} onChange={(e) => patch({ morningTime: e.target.value })}/></label><label>晚间提醒<input type="time" value={settings.eveningTime} onChange={(e) => patch({ eveningTime: e.target.value })}/></label></div><div className="dedupe-note"><ShieldCheck size={16}/><span><b>频控与去重已开启</b>任务 ID、截止日期和提醒窗口共同生成去重键，避免重复触达。</span></div><button className="button button-primary" onClick={save}>保存提醒设置</button></div></div>; }

function generateStageTasks(existing: TodayTask[]) { const ids = new Set(existing.map((task) => task.id)); return applications.flatMap((app): TodayTask[] => { const map: Record<string, Pick<TodayTask, "title" | "description" | "priority" | "actionType" | "actionHref">> = { Preparing: { title: `完成 ${app.company} 申请材料`, description: "申请处于准备阶段，建议先完成定制简历和 Cover Letter。", priority: "high", actionType: "resume", actionHref: "/resume" }, Applied: { title: `检查 ${app.company} 跟进节点`, description: "根据投递日期判断是否需要发送 Follow-up。", priority: "medium", actionType: "application", actionHref: "/application-assistant" }, Interview: { title: `准备 ${app.company} 面试`, description: "申请进入 Interview 阶段，完成岗位问题与 STAR 故事练习。", priority: "high", actionType: "interview", actionHref: "/application-assistant" }, Offer: { title: `复盘 ${app.company} Offer`, description: "整理薪资、签证、团队和截止时间，准备决策。", priority: "high", actionType: "application", actionHref: "/applications" }, Interested: { title: `评估 ${app.company} 岗位`, description: "查看匹配度与截止时间，决定是否开始申请。", priority: "low", actionType: "job", actionHref: `/jobs/${app.jobId}` } }; const config = map[app.status]; const id = `stage-${app.id}-${app.status.toLowerCase()}`; if (!config || ids.has(id)) return []; const dueAt = new Date(); dueAt.setHours(config.priority === "high" ? 17 : 20, 0, 0, 0); return [{ id, ...config, status: "todo", dueAt: dueAt.toISOString(), source: "automatic", applicationId: app.id, postponedCount: 0 }]; }); }
function priorityRank(priority: TaskPriority) { return priority === "high" ? 0 : priority === "medium" ? 1 : 2; }
function formatDue(value: string) { const date = new Date(value); const today = new Date(); if (date.toDateString() === today.toDateString()) return `今天 ${date.toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit" })}`; return date.toLocaleDateString("zh-CN", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }); }
function toDateTimeInput(value: Date) { const local = new Date(value.getTime() - value.getTimezoneOffset() * 60000); return local.toISOString().slice(0, 16); }
