"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ArrowRight, BriefcaseBusiness, CalendarClock, Check, CheckCircle2, Clock3, Loader2, RefreshCw, Sparkles } from "lucide-react";
import { apiRequest, jsonBody } from "@/lib/api-client";

type Task={id:number;title:string;detail?:string;priority:string;completed:boolean;taskDate?:string;updatedAt?:string;refs?:{applicationId?:number}}; type Dashboard={today:{tasks:Task[];scheduled:Task[]}}; type Board={statistics:Record<string,number>;total:number};
export function TodayLive(){const [dashboard,setDashboard]=useState<Dashboard|null>(null);const [board,setBoard]=useState<Board|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [busy,setBusy]=useState<number|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const [d,b]=await Promise.all([apiRequest<Dashboard>("/api/v4/career/dashboard"),apiRequest<Board>("/api/v4/applications/board")]);setDashboard(d);setBoard(b);}catch(err){setError(err instanceof Error?err.message:"工作台加载失败");}finally{setLoading(false);}},[]);useEffect(()=>{load();},[load]);
 async function toggle(task:Task){if(busy)return;setBusy(task.id);setError("");try{await apiRequest(`/api/v4/today/tasks/${task.id}`,{method:"PATCH",body:jsonBody({completed:!task.completed,updatedAt:task.updatedAt})});await load();}catch(err){setError(err instanceof Error?err.message:"任务更新失败");}finally{setBusy(null);}}
 async function defer(task:Task){if(busy)return;setBusy(task.id);try{await apiRequest(`/api/v4/today/tasks/${task.id}/defer`,{method:"POST",body:jsonBody({days:1})});await load();}catch(err){setError(err instanceof Error?err.message:"延期失败");}finally{setBusy(null);}}
 const tasks=dashboard?.today.tasks||[];const pending=tasks.filter(t=>!t.completed);return <div className="zy-today"><div className="zy-page-head"><div><h1>今天，先处理最重要的一项。</h1><p>工作台只展示真实申请和任务。小程序完成任务后，这里刷新即可看到同一状态。</p></div><button className="zy-button zy-button-secondary" onClick={load}><RefreshCw size={15}/>刷新</button></div>{error&&<p className="zy-alert">{error}</p>}{loading?<div className="zy-state-card"><Loader2 className="spin"/>正在整理今天的工作…</div>:<><section className="zy-today-summary"><div className="zy-today-primary">{pending[0]?<><h2>{pending[0].title}</h2><p>{pending[0].detail||"完成后，申请会继续向下一阶段推进。"}</p><button className="zy-button zy-button-primary" onClick={()=>toggle(pending[0])} disabled={busy===pending[0].id}><Check size={15}/>标记完成</button></>:<><h2>今天的重点任务已完成</h2><p>可以检查申请管线，确认是否还有需要跟进的记录。</p><Link className="zy-button zy-button-primary" href="/applications">查看申请管线<ArrowRight size={15}/></Link></>}</div><div className="zy-today-stats"><article><BriefcaseBusiness size={19}/><span><b>{board?.statistics?.preparing||0}</b>准备中</span></article><article><ArrowRight size={19}/><span><b>{board?.statistics?.applied||0}</b>已投递</span></article><article><CalendarClock size={19}/><span><b>{board?.statistics?.interview||0}</b>面试中</span></article><article><CheckCircle2 size={19}/><span><b>{tasks.filter(t=>t.completed).length}</b>今日完成</span></article></div></section><div className="zy-today-layout"><section className="zy-today-list"><header><div><h2>今日任务</h2></div><span>{pending.length} 项待完成</span></header>{tasks.length?tasks.map(task=><article className={task.completed?"done":""} key={task.id}><button className="zy-task-check" aria-label={task.completed?"标记为未完成":"标记完成"} onClick={()=>toggle(task)} disabled={busy===task.id}>{task.completed&&<Check size={13}/>}</button><div><h3>{task.title}</h3><p>{task.detail||"来自你的求职计划"}</p></div><span>{task.priority==="high"?"优先":task.priority==="low"?"稍后":"今天"}</span>{!task.completed&&<button className="zy-defer" onClick={()=>defer(task)}>明天处理</button>}</article>):<div className="zy-empty"><CheckCircle2 size={26}/><h2>今天没有待办</h2><p>新增申请或使用 AI 专家后，相关任务会显示在这里。</p></div>}</section><aside className="zy-today-side"><section><span className="zy-icon-box"><Sparkles size={20}/></span><h2>遇到卡点，问 AI 专家</h2><p>结合当前申请、简历版本和已确认材料，获得可以执行的建议。</p><Link href="/ai-career">开始问询<ArrowRight size={14}/></Link></section><section><h2>接下来</h2>{dashboard?.today.scheduled?.slice(0,5).map(task=><div key={task.id}><Clock3 size={14}/><span><b>{task.title}</b><small>{task.taskDate}</small></span></div>)}{!dashboard?.today.scheduled?.length&&<p>还没有计划到之后的任务。</p>}</section></aside></div></>}</div>}
